### ISSUE TITLE
"file name too long" error

### ISSUE THREAD

**Issue by mr-martian** [apertium/apertium-lint#5]
```
Traceback (most recent call last):
  File "/usr/local/bin/apertium-lint", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/apertium_lint/__init__.py", line 87, in main
    lint_path(fname, args, count)
  File "/usr/local/lib/python3.10/dist-packages/apertium_lint/__init__.py", line 66, in lint_path
    if ent.is_file():
OSError: [Errno 36] File name too long: '/home/jwashin1/ling073/ling073-iii/README.md'
```

the proper thing to report here is probably "something has gone very wrong with this file" (in this instance it had somehow been set as  a symlink to the contents of `README` rather than to the file `README`)

**Comment by Chirag-01** [comment]
Hi Mentor,

I hope this message finds you well. I'm interested in working on this issue, but I'm having trouble with the installation process. I attempted to clone the repository, but I'm having difficulty running it.

Would you be able to give me a list of commands that I can use to get the repository up and running? Any help you can provide would be greatly appreciated.

Thank you so much for your time and assistance.

**Comment by mr-martian** [comment]
@Chirag-01 issue comments is not the appropriate place for such discussion. Come talk on IRC or the mailing list for such things.
